CONFIG_MAIN_STACK_SIZE=4096
CONFIG_LOG=y

CONFIG_FLASH=y
CONFIG_SPI=y
CONFIG_SPI_NOR=y
CONFIG_SPI_NOR_SFDP_RUNTIME=y
# CONFIG_FLASH_JESD216_API=y  /* necessario apenas para flash_sfdp_read() */
# Para usar SFDP do devicetree (sem ler do chip no boot):
# trocar SFDP_RUNTIME por SFDP_DEVICETREE e descomentar sfdp-bfp no overlay
# CONFIG_SPI_NOR_SFDP_DEVICETREE=y


# Configure dependencies for CONFIG_IMG_MANAGER  
CONFIG_STREAM_FLASH=y
CONFIG_FLASH_MAP=y
